version: '3.9'

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    command: ./entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - memory

  memory:
    container_name: rediska
    image: redis:7.4.1
    volumes:
      - ./data/redis/:/redis/data
    env_file:
      - .env
    ports:
      - 6379:6379

  memory-ui:
    container_name: memory-ui
    image: redis/redisinsight:2.62
    env_file:
      - .env
    volumes:
      - ./data/ri/:/ri/data
    ports:
      - 5540:5540
    depends_on:
      - memory

  db:
    container_name: postgres
    image: postgres:17.2
    volumes:
      - ./data/postgres/:/var/lib/postgres
    ports:
      - 5432:5432
    env_file:
      .env
