version: '3.9'

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    command: ./entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./data/postgres/:/var/lib/postgres
    ports:
      - '5432:5432'
    env_file:
      .env
