version: '3.9'

services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/app
    command: python3 main.py
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgresdb
    image: postgres:16
    volumes:
      - /var/lib/postgres
    ports:
      - 5432:5432
    env_file:
      - .env
