line-length = 100
extend-ignore = ["E701", "E301"]

[lint]
extend-select = ["E501"]
flake8-implicit-str-concat.allow-multiline = false

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
