"""

Revision ID: 506a5dea3930
Revises: 8211ffe0ce4b
Create Date: 2024-12-08 13:36:06.238107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506a5dea3930'
down_revision: Union[str, None] = '8211ffe0ce4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permission_user_user_id_fkey', 'permission_user', type_='foreignkey')
    op.drop_constraint('permission_user_permission_id_fkey', 'permission_user', type_='foreignkey')
    op.create_foreign_key(None, 'permission_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'permission_user', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission_user', type_='foreignkey')
    op.drop_constraint(None, 'permission_user', type_='foreignkey')
    op.create_foreign_key('permission_user_permission_id_fkey', 'permission_user', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key('permission_user_user_id_fkey', 'permission_user', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
