"""

Revision ID: 6a2604092c8d
Revises: 
Create Date: 2024-12-10 22:27:45.616143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2604092c8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_codename', 'permissions', type_='unique')
    op.drop_constraint('unique_username', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_username', 'users', ['username'])
    op.create_unique_constraint('unique_codename', 'permissions', ['codename'])
    # ### end Alembic commands ###
