"""Add index to the field

Revision ID: b17e8de1a541
Revises: 9346c7287a06
Create Date: 2024-12-08 18:29:21.224647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17e8de1a541'
down_revision: Union[str, None] = '9346c7287a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permissions_codename_key', 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_codename'), 'permissions', ['codename'], unique=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_permissions_codename'), table_name='permissions')
    op.create_unique_constraint('permissions_codename_key', 'permissions', ['codename'])
    # ### end Alembic commands ###
