from src.core.dto import users, permissions


class IUserRepository:
    async def add(self, dto: users.AddUserDTO) -> users.UserDTO: ...

    async def get(self, id: int) -> users.UserDTO: ...


class IPermissionRepository:
    async def get_by_codename(self, codename: str) -> permissions.PermissionDTO: ...

    async def add(self, dto: permissions.AddPermissionDTO) -> permissions.PermissionDTO: ...

    async def get(self, id: int) -> permissions.PermissionDTO: ...
